# netlify.toml
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: https:;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline' https://unpkg.com https://www.google.com https://www.gstatic.com https://www.googletagmanager.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://drive.google.com https://www.google.com https://*.netlify.app https://ipapi.co https://*.google-analytics.com;
      frame-src 'self' https://open.spotify.com https://www.google.com https://archive.org https://drive.google.com;
      worker-src 'self' blob:;
      media-src 'self' *.archive.org https://drive.google.com;
    """

# Specific redirect for the mentioned URL
[[redirects]]
  from = "/download/we-offer-you-our-gifts-by-emmanuel-atuanya/"
  to = "/song/We-offer-you-our-gifts-by-Emmanuel-Atuanya"
  status = 301
  force = true

# General redirect for other /download/ to /song/ URLs
[[redirects]]
  from = "/download/:slug/"
  to = "/song/:slug"
  status = 301
  force = true

# Combined redirect for /song/ URLs: lowercase and strip suffixes
[[redirects]]
  from = "/song/:id(*:*)"
  to = "/song/:splat"
  status = 301
  force = true
  [redirects.functions]
    _lowercase = "splat"
  [redirects.parameters]
    splat = ":id"

# Existing SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/index.html"
  status = 200

[build]
  functions = "netlify/functions"
  [build.environment]
    NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
