[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: https://images.unsplash.com https://images.pexels.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline' https://unpkg.com;
      connect-src 'self' https://*.supabase.co https://drive.google.com;
      frame-src 'self' https://open.spotify.com;
      worker-src 'self' blob:;
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/index.html"
  status = 200
