# netlify.toml
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: https:;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline' https://unpkg.com https://www.google.com https://www.gstatic.com;
      connect-src 'self' https://*.supabase.co https://drive.google.com https://www.google.com https://*.netlify.app;
      frame-src 'self' https://open.spotify.com https://www.google.com https://archive.org;
      worker-src 'self' blob:;
      media-src 'self' *.archive.org https://drive.google.com;
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/index.html"
  status = 200

[build]
  functions = "netlify/functions"
  [build.environment]
    NODE_VERSION = "18"
