[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: https://images.unsplash.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline';
      connect-src 'self' https://*.supabase.co;
    """
